language: c
compiler:
  - gcc
  - clang
# Change this to your needs
# Change this to your needs
before_script:
  - wget 'https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2' -O /tmp/htslib-1.9.tar.bz2
  - tar -xjf /tmp/htslib-1.9.tar.bz2
  - cd htslib-1.9/
  - make libhts.a htslib_static.mk
  - cd ..
script: libtoolize; ./bootstrap && ./configure --with-htslib=${PWD}/htslib-1.9 && make
