# Dependencies
highlighter:      rouge

# Permalinks
# http://jekyllrb.com/docs/upgrading/: "Starting with v2.0, however, absolute permalinks will become opt-out, meaning Jekyll will default to using absolute permalinks instead of relative permalinks."
permalink:        pretty
# hyde original: relative_permalinks: true

# Setup
title:            LoFreq
tagline:          'Fast and sensitive variant calling from next-gen sequencing data'
description:      'Fast and sensitive variant calling from next-gen sequencing data'
#url:              http://csb5.github.io
baseurl:          /lofreq
# baseurl should be set to /project according to
# see project-pages notes on http://jekyllrb.com/docs/github-pages/
# and a local serve call should then use --baseurl ""
# but that breaks relative css reference etc
author:
  name:           'Andreas Wilm'
  url:            https://twitter.com/mdo

paginate:         5
paginate_path:    blog/page:num

# Custom vars
#hyde_version:    2.1.0
#hyde_commit:     e2a6f89

sourceforge:
  download:     https://sourceforge.net/projects/lofreq/files/
github:
  repo:         https://github.com/CSB5/lofreq
  dist:         https://github.com/CSB5/lofreq/tree/master/dist

# exclude this from build
exclude:	[tmp/, jekyll.README, FIXME, LICENSE.md, .gitignore,
	         Makefile, Makefile.in, aclocal.m4, autom4te.cache/,
             compile, config.guess, config.log, config.status,
             config.sub, configure, depcomp, install-sh, libtool,
             ltmain.sh, m4/, missing,
              src/, tests/]
